[tool.poetry]
name = "llm-google-gemini"
version = "0.1.0"
description = ""
authors = ["Jiliar Silgado <jiliar.silgado@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
